// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	AddMetricGauge(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error)
	AddMetricCounter(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error)
	GetMetricValue(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*GetMetricValueResponse, error)
	GetMetricNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMetricNamesResponse, error)
	UpdateMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error)
	GetMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Metric, error)
	UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*StdResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) AddMetricGauge(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error) {
	out := new(StdResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/AddMetricGauge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) AddMetricCounter(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error) {
	out := new(StdResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/AddMetricCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetMetricValue(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*GetMetricValueResponse, error) {
	out := new(GetMetricValueResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/GetMetricValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetMetricNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMetricNamesResponse, error) {
	out := new(GetMetricNamesResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/GetMetricNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*StdResponse, error) {
	out := new(StdResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/UpdateMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Metric, error) {
	out := new(Metric)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/GetMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*StdResponse, error) {
	out := new(StdResponse)
	err := c.cc.Invoke(ctx, "/grpc.Metrics/UpdateMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	AddMetricGauge(context.Context, *Metric) (*StdResponse, error)
	AddMetricCounter(context.Context, *Metric) (*StdResponse, error)
	GetMetricValue(context.Context, *Metric) (*GetMetricValueResponse, error)
	GetMetricNames(context.Context, *Empty) (*GetMetricNamesResponse, error)
	UpdateMetric(context.Context, *Metric) (*StdResponse, error)
	GetMetric(context.Context, *Metric) (*Metric, error)
	UpdateMetrics(context.Context, *UpdateMetricsRequest) (*StdResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) AddMetricGauge(context.Context, *Metric) (*StdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMetricGauge not implemented")
}
func (UnimplementedMetricsServer) AddMetricCounter(context.Context, *Metric) (*StdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMetricCounter not implemented")
}
func (UnimplementedMetricsServer) GetMetricValue(context.Context, *Metric) (*GetMetricValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricValue not implemented")
}
func (UnimplementedMetricsServer) GetMetricNames(context.Context, *Empty) (*GetMetricNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricNames not implemented")
}
func (UnimplementedMetricsServer) UpdateMetric(context.Context, *Metric) (*StdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetric not implemented")
}
func (UnimplementedMetricsServer) GetMetric(context.Context, *Metric) (*Metric, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetric not implemented")
}
func (UnimplementedMetricsServer) UpdateMetrics(context.Context, *UpdateMetricsRequest) (*StdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetrics not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_AddMetricGauge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).AddMetricGauge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/AddMetricGauge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).AddMetricGauge(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_AddMetricCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).AddMetricCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/AddMetricCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).AddMetricCounter(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetMetricValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetricValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/GetMetricValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetricValue(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetMetricNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetricNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/GetMetricNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetricNames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/UpdateMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/GetMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Metrics/UpdateMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateMetrics(ctx, req.(*UpdateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMetricGauge",
			Handler:    _Metrics_AddMetricGauge_Handler,
		},
		{
			MethodName: "AddMetricCounter",
			Handler:    _Metrics_AddMetricCounter_Handler,
		},
		{
			MethodName: "GetMetricValue",
			Handler:    _Metrics_GetMetricValue_Handler,
		},
		{
			MethodName: "GetMetricNames",
			Handler:    _Metrics_GetMetricNames_Handler,
		},
		{
			MethodName: "UpdateMetric",
			Handler:    _Metrics_UpdateMetric_Handler,
		},
		{
			MethodName: "GetMetric",
			Handler:    _Metrics_GetMetric_Handler,
		},
		{
			MethodName: "UpdateMetrics",
			Handler:    _Metrics_UpdateMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
