version: '3'
services:
  postgres:
    container_name: pggo
    image: postgres:13
    hostname: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "./docker_db:/docker-entrypoint-initdb.d"
    #  - ".:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"